language: python

python:
    - "3.6"
    
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install coveralls
  - pip install pytest
  - pip install coverage
  - pip install nose

script:
  - coverage erase
  - pytest
  - nosetests --with-coverage
  - coverage report -m

after_success:
  - codecov
  - coveralls