language: python

python:
    - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls


script:
  - coverage erase
  - coverage run --source='.' manage.py test
  - coverage report -m

after_success:
  - codecov
  - coveralls