# Generated by Django 2.0.6 on 2018-08-16 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(db_column='article',
                                              on_delete=django.db.models
                                              .deletion.CASCADE,
                                              to='articles.Article')),
                ('dislikes', models.ManyToManyField(blank=True,
                                                    related_name
                                                    ='comment_dislikes',
                                                    to=settings
                                                    .AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True,
                                                 related_name='comment_likes',
                                                 to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(default=None, null=True,
                                             on_delete=django.db.models
                                             .deletion.CASCADE,
                                             related_name='children',
                                             to='comments.Comment')),
                ('user', models.ForeignKey(db_column='user',
                                           on_delete=django.db.models
                                           .deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('createdAt',),
            },
        ),
        migrations.CreateModel(
            name='CommentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('parent_comment',
                 models.ForeignKey(db_column='parent_comment',
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='comments.Comment')),
            ],
        ),
    ]
