# Generated by Django 2.0.6 on 2018-08-15 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('parent_comment', models.ForeignKey(db_column='parent_comment', on_delete=django.db.models.deletion.CASCADE, to='comments.Comment')),
            ],
        ),
    ]
